name: Build and Push Docker

on:
  workflow_call:
    secrets:
      docker_hub_username:
        required: true
      docker_hub_access_token:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Build and release a new version of Docker image
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_access_token }}
      - name: Build and push Docker image
        run: |
          CUR_VER="`./gradlew currentVersion -q -Prelease.quiet`-feature-${GITHUB_SHA}"
          ./gradlew build dockerPushDockerHub \
            -PdockerHubRegistry=${{ secrets.docker_hub_username }} \
            -PdockerTagVersion=${CUR_VER} \
            --stacktrace --debug
