name: release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and release a new Git tag
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Release
        id: release
        run: |
          ./gradlew release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }}
          CUR_VER=`./gradlew currentVersion -q -Prelease.quiet`
          echo "CURRENT_VERSION=$CUR_VER" >> $GITHUB_ENV
          echo "RELEASE_BRANCH_VERSION=$(echo $CUR_VER | cut -d '.' -f -2)" >> $GITHUB_ENV
          echo "### Version ${CUR_VER} released! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Create release branch for a new created git tag
        if: github.ref == 'refs/heads/master'
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/release/${{ env.RELEASE_BRANCH_VERSION }}'
