name: terraform-plan

on:
  workflow_call:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Setup ssh key to download terraform modules from private repositories
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 400 ~/.ssh/id_rsa
          git config --global user.name "Dawid Aleksandrowicz"
          git config --global user.email "daleksandrowicz@griddynamics.com"
          tee -a ~/.ssh/config <<EOF
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/id_rsa
          EOF
      - name: Terraform Init
        id: init
        run: |
          cd ./hardware
          terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
