name: terraform-apply

on:
  workflow_call:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    name: Deploy environment
    defaults:
      run:
        working-directory: hardware
    outputs:
      region: ${{ steps.output-region.outputs.region }}
      cluster_name: ${{ steps.output-cluster-name.outputs.cluster_name }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      # - name: Deploy terraform
      #   if: github.ref == 'refs/heads/master'
      #   run: terraform apply -auto-approve
      - name: Output region
        id: output-region
        run: echo "region=$(terraform output -raw region)" >> $GITHUB_OUTPUT
      - name: Output cluster_name
        id: output-cluster-name
        run: echo "region=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
