name: terraform-plan

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/hardware
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true
      - name: Setup ssh key to download terraform modules from private repositories
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 400 ~/.ssh/id_rsa
          git config --global user.name "Dawid Aleksandrowicz"
          git config --global user.email "daleksandrowicz@griddynamics.com"
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          tee -a ~/.ssh/config <<EOF
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/id_rsa
          EOF
      - name: Terraform Init
        id: init
        run: |
          terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
